10 REM INSTRUCTIONS FOR "SUPER STARTREK"  MAR 5, 1978
15 REM PAGED FOR A 30-ROW SCREEN, THEN RUNS THE GAME
20 FOR I=1 TO 8:PRINT:NEXT I
21 PRINT TAB(21);"*************************************"
22 PRINT TAB(21);"*                                   *"
23 PRINT TAB(21);"*                                   *"
24 PRINT TAB(21);"*      * * SUPER STAR TREK * *      *"
25 PRINT TAB(21);"*                                   *"
26 PRINT TAB(21);"*                                   *"
27 PRINT TAB(21);"*************************************"
30 FOR I=1 TO 9:PRINT:NEXT I
40 INPUT "DO YOU NEED INSTRUCTIONS (Y/N)";K$:IF K$="N" THEN 2000
50 PRINT CHR$(12);
100 PRINT"      INSTRUCTIONS FOR 'SUPER STAR TREK'"
110 PRINT
120 PRINT"1. WHEN YOU SEE \COMMAND ?\ PRINTED, ENTER ONE OF THE LEGAL"
130 PRINT"     COMMANDS (NAV,SRS,LRS,PHA,TOR,SHE,DAM,COM, OR XXX)."
140 PRINT"2. IF YOU SHOULD TYPE IN AN ILLEGAL COMMAND, YOU'LL GET A SHORT"
150 PRINT"     LIST OF THE LEGAL COMMANDS PRINTED OUT."
160 PRINT"3. SOME COMMANDS REQUIRE YOU TO ENTER DATA (FOR EXAMPLE, THE"
170 PRINT"     'NAV' COMMAND COMES BACK WITH 'COURSE (1-9) ?'.)  IF YOU"
180 PRINT"     TYPE IN ILLEGAL DATA (LIKE NEGATIVE NUMBERS), THAN COMMAND"
190 PRINT"     WILL BE ABORTED"
200 PRINT
210 PRINT"     THE GALAXY IS DIVIDED INTO AN 8 X 8 QUADRANT GRID,"
220 PRINT"AND EACH QUADRANT IS FURTHER DIVIDED INTO AN 8 X 8 SECTOR GRID."
230 PRINT
240 PRINT"     YOU WILL BE ASSIGNED A STARTING POINT SOMEWHERE IN THE"
250 PRINT"GALAXY TO BEGIN A TOUR OF DUTY AS COMANDER OF THE STARSHIP"
260 PRINT"\ENTERPRISE\; YOUR MISSION: TO SEEK AND DESTROY THE FLEET OF"
270 PRINT"KLINGON WARWHIPS WHICH ARE MENACING THE UNITED FEDERATION OF"
280 PRINT"PLANETS."
290 PRINT
300 PRINT"     YOU HAVE THE FOLLOWING COMMANDS AVAILABLE TO YOU AS CAPTAIN"
310 PRINT"OF THE STARSHIP ENTERPRISE:"
320 GOSUB 3000
400 PRINT"\NAV\ COMMAND = WARP ENGINE CONTROL --"
410 PRINT"     COURSE IS IN A CIRCULAR NUMERICAL      4  3  2"
420 PRINT"     VECTOR ARRANGEMENT AS SHOWN             . . ."
430 PRINT"     INTEGER AND REAL VALUES MAY BE           ..."
440 PRINT"     USED.  (THUS COURSE 1.5 IS HALF-     5 ---*--- 1"
450 PRINT"     WAY BETWEEN 1 AND 2                      ..."
460 PRINT"                                             . . ."
470 PRINT"     VALUES MAY APPROACH 9.0, WHICH         6  7  8"
480 PRINT"     ITSELF IS EQUIVALENT TO 1.0"         
490 PRINT"                                            COURSE"
500 PRINT"     ONE WARP FACTOR IS THE SIZE OF "
510 PRINT"     ONE QUADTANT.  THEREFORE, TO GET"
520 PRINT"     FROM QUADRANT 6,5 TO 5,5, YOU WOULD"
530 PRINT"     USE COURSE 3, WARP FACTOR 1."
540 PRINT
550 PRINT"\SRS\ COMMAND = SHORT RANGE SENSOR SCAN"
560 PRINT"     SHOWS YOU A SCAN OF YOUR PRESENT QUADRANT."
570 PRINT
580 PRINT"     SYMBOLOGY ON YOUR SENSOR SCREEN IS AS FOLLOWS:"
590 PRINT"        <*> = YOUR STARSHIP'S POSITION"
600 PRINT"        +K+ = KLINGON BATTLE CRUISER"
610 PRINT"        >!< = FEDERATION STARBASE (REFUEL/REPAIR/RE-ARM HERE!)"
620 PRINT"         *  = STAR"
630 PRINT
640 PRINT"     A CONDENSED 'STATUS REPORT' WILL ALSO BE PRESENTED."
650 GOSUB 3000
700 PRINT"\LRS\ COMMAND = LONG RANGE SENSOR SCAN"
710 PRINT"     SHOWS CONDITIONS IN SPACE FOR ONE QUADRANT ON EACH SIDE"
720 PRINT"     OF THE ENTERPRISE (WHICH IS IN THE MIDDLE OF THE SCAN)"
730 PRINT"     THE SCAN IS CODED IN THE FORM \###\, WHERE TH UNITS DIGIT"
740 PRINT"     IS THE NUMBER OF STARS, THE TENS DIGIT IS THE NUMBER OF"
750 PRINT"     STARBASES, AND THE HUNDRESDS DIGIT IS THE NUMBER OF"
760 PRINT"     KLINGONS."
770 PRINT
780 PRINT"     EXAMPLE - 207 = 2 KLINGONS, NO STARBASES, & 7 STARS."
790 PRINT
800 PRINT"\PHA\ COMMAND = PHASER CONTROL."
810 PRINT"     ALLOWS YOU TO DESTROY THE KLINGON BATTLE CRUISERS BY "
820 PRINT"     ZAPPING THEM WITH SUITABLY LARGE UNITS OF ENERGY TO"
830 PRINT"     DEPLETE THEIR SHIELD POWER.  (REMBER, KLINGONS HAVE"
840 PRINT"     PHASERS TOO!)"
850 PRINT
860 PRINT"\TOR\ COMMAND = PHOTON TORPEDO CONTROL"
870 PRINT"     TORPEDO COURSE IS THE SAME AS USED IN WARP ENGINE CONTROL"
880 PRINT"     IF YOU HIT THE KLINGON VESSEL, HE IS DESTROYED AND"
890 PRINT"     CANNOT FIRE BACK AT YOU.  IF YOU MISS, YOU ARE SUBJECT TO"
900 PRINT"     HIS PHASER FIRE.  IN EITHER CASE, YOU ARE ALSO SUBJECT TO "
910 PRINT"     THE PHASER FIRE OF ALL OTHER KLINGONS IN THE QUADRANT."
920 PRINT
930 PRINT"     THE LIBRARY-COMPUTER (\COM\ COMMAND) HAS AN OPTION TO "
940 PRINT"     COMPUTE TORPEDO TRAJECTORY FOR YOU (OPTION 2)"
950 GOSUB 3000
1000 PRINT"\SHE\ COMMAND = SHIELD CONTROL"
1010 PRINT"     DEFINES THE NUMBER OF ENERGY UNITS TO BE ASSIGNED TO THE"
1020 PRINT"     SHIELDS.  ENERGY IS TAKEN FROM TOTAL SHIP'S ENERGY.  NOTE"
1030 PRINT"     THAN THE STATUS DISPLAY TOTAL ENERGY INCLUDES SHIELD ENERGY"
1040 PRINT
1050 PRINT"\DAM\ COMMAND = DAMMAGE CONTROL REPORT"
1060 PRINT"     GIVES THE STATE OF REPAIR OF ALL DEVICES.  WHERE A NEGATIVE"
1070 PRINT"     'STATE OF REPAIR' SHOWS THAT THE DEVICE IS TEMPORARILY"
1080 PRINT"     DAMAGED."
1090 GOSUB 3000
1200 PRINT"\COM\ COMMAND = LIBRARY-COMPUTER"
1210 PRINT"     THE LIBRARY-COMPUTER CONTAINS SIX OPTIONS:"
1220 PRINT"     OPTION 0 = CUMULATIVE GALACTIC RECORD"
1230 PRINT"        THIS OPTION SHOWES COMPUTER MEMORY OF THE RESULTS OF ALL"
1240 PRINT"        PREVIOUS SHORT AND LONG RANGE SENSOR SCANS"
1250 PRINT"     OPTION 1 = STATUS REPORT"
1260 PRINT"        THIS OPTION SHOWS THE NUMBER OF KLINGONS, STARDATES,"
1270 PRINT"        AND STARBASES REMAINING IN THE GAME."
1280 PRINT"     OPTION 2 = PHOTON TORPEDO DATA"
1290 PRINT"        WHICH GIVES DIRECTIONS AND DISTANCE FROM THE ENTERPRISE"
1300 PRINT"        TO ALL KLINGONS IN YOUR QUADRANT"
1310 PRINT"     OPTION 3 = STARBASE NAV DATA"
1320 PRINT"        THIS OPTION GIVES DIRECTION AND DISTANCE TO ANY "
1330 PRINT"        STARBASE WITHIN YOUR QUADRANT"
1340 PRINT"     OPTION 4 = DIRECTION/DISTANCE CALCULATOR"
1350 PRINT"        THIS OPTION ALLOWS YOU TO ENTER COORDINATES FOR"
1360 PRINT"        DIRECTION/DISTANCE CALCULATIONS"
1370 PRINT"     OPTION 5 = GALACTIC /REGION NAME/ MAP"
1380 PRINT"        THIS OPTION PRINTS THE NAMES OF THE SIXTEEN MAJOR "
1390 PRINT"        GALACTIC REGIONS REFERRED TO IN THE GAME."
1400 GOSUB 3000
2000 PRINT CHR$(12);"Loading, about 17 seconds..."
2010 RUN "ROM:GAME.BAS"
3000 PRINT:INPUT "Press ENTER";K$:PRINT CHR$(12);:RETURN
