name: Web

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      source:
        description: Branch, tag or commit to build
      emulator:
        description: Emulator, such as v0.36

jobs:
  web:
    uses: picocomputer/.github/.github/workflows/web.yml@main
    with:
      source: ${{ inputs.source }}
      emulator: ${{ inputs.emulator }}
    permissions:
      contents: read
      pages: write
      id-token: write
